// Generated by scripts/import-linkedin-export.js from your LinkedIn data export.
// Safe to hand-edit afterward — re-running the importer will overwrite this file,
// so commit hand-edits and review the diff on your next import.

var CERTIFICATIONS = [
    {
        name: "Microsoft SQL Server 2022 Essential Training",
        issuer: "LinkedIn",
        issueDate: "02/2026",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/64fc4964565839e3fc83ae661675970bf2f6b1c697df6b413d78dfc5a3894d12",
        licenseNumber: null
    },
    {
        name: "Introduction to Fintech",
        issuer: "LinkedIn",
        issueDate: "02/2026",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/0a4e2b0cb412676a596b098c05760d55c2421de5d188188cedf226f83cec933c",
        licenseNumber: null
    },
    {
        name: "Visual Studio Essential Training",
        issuer: "LinkedIn",
        issueDate: "11/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/6bbe1d10d265caa5f60bbbf8bb8c4b5edec860a3a05e761fffdc925fb26e2c92",
        licenseNumber: null
    },
    {
        name: "Software Testing Foundations: Bug Writing and Management",
        issuer: "LinkedIn",
        issueDate: "09/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/2d8998891713582d39aa5906046d9b24fc53f5825e3c6e7e580ab7f7985a45b4",
        licenseNumber: null
    },
    {
        name: "System Administration and IT Infrastructure Services",
        issuer: "Google",
        issueDate: "03/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/records/6HJW0U815ORG",
        licenseNumber: "6HJW0U815ORG"
    },
    {
        name: "IT Security: Defense against the digital dark arts",
        issuer: "Google",
        issueDate: "03/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/records/MA043EKGSPF6",
        licenseNumber: "MA043EKGSPF6"
    },
    {
        name: "Google IT Support",
        issuer: "Google",
        issueDate: "03/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/specialization/G5YPDJ9NY7OL",
        licenseNumber: "G5YPDJ9NY7OL"
    },
    {
        name: "MATLAB Onramp",
        issuer: "MathWorks",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://matlabacademy.mathworks.com/progress/share/certificate.html?id=5f86a35a-ee87-4794-9562-e20a681e1028&",
        licenseNumber: "5f86a35a-ee87-4794-9562-e20a681e1028&"
    },
    {
        name: "Learning QGIS",
        issuer: "LinkedIn",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/d3621b47a8018d687d108da1c739cccc17e8d713bd35fd234bae6da44f0351b3",
        licenseNumber: null
    },
    {
        name: "Primavera P6 Essential Training",
        issuer: "LinkedIn",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/cdd666e39ed2209f4ad1bb301ab9cbf887e4ba9c9a4df106694a83600585938f",
        licenseNumber: null
    },
    {
        name: "Procore Admin Certification: Series Certificate",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/ph964av56gt3",
        licenseNumber: "ph964av56gt3"
    },
    {
        name: "Procore Certified: Subcontractor",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/5n56pchntex3",
        licenseNumber: "5n56pchntex3"
    },
    {
        name: "Procore Certification: BIM Manager",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/iwagtg3ru36c",
        licenseNumber: "iwagtg3ru36c"
    },
    {
        name: "Procore Certified: Payee Procore Pay",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/5aoor2inr3dk",
        licenseNumber: "5aoor2inr3dk"
    },
    {
        name: "Procore Certified: Project Manager (Core Tools)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/7ut2nbk6mjfb",
        licenseNumber: "7ut2nbk6mjfb"
    },
    {
        name: "Procore Certified: Project Manager at GC (Financial Management)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/feueukicnyyi",
        licenseNumber: "feueukicnyyi"
    },
    {
        name: "Procore Certified: Project Manager (Field Productivity)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/avzh8s95rqxn",
        licenseNumber: "avzh8s95rqxn"
    },
    {
        name: "Procore Certified: Project Manager at GC (Workforce Planning)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/v4y9j3nzza72",
        licenseNumber: "v4y9j3nzza72"
    },
    {
        name: "Procore Certified: Project Manager (Quality & Safety)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/b5zgmhdxatop",
        licenseNumber: "b5zgmhdxatop"
    },
    {
        name: "Procore Certified: Project Manager (Project Management)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/f4hzb39jwjdq",
        licenseNumber: "f4hzb39jwjdq"
    },
    {
        name: "Procore Certified: Project Manager at GC (Preconstruction)",
        issuer: "Procore Technologies",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://verify.skilljar.com/c/cxoh92mebwyw",
        licenseNumber: "cxoh92mebwyw"
    },
    {
        name: "Windows 10 for IT Support: Troubleshooting Basics",
        issuer: "LinkedIn",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/202fc9d84d41fcec111827d0c196a40365d84f3b60facbf7cde16a82436966b4",
        licenseNumber: null
    },
    {
        name: "IT Help Desk for Beginners",
        issuer: "LinkedIn",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/861ac2b4200c64f024251f2c80e3444d129fcf248a7f1a10b83c33984610dca3",
        licenseNumber: null
    },
    {
        name: "Technical Support Fundamentals",
        issuer: "Google",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/records/PPYLVZPMKZNC",
        licenseNumber: "PPYLVZPMKZNC"
    },
    {
        name: "The Bits and Bytes of Computer Networking",
        issuer: "Google",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/records/ZF8XPILSLBXY",
        licenseNumber: "ZF8XPILSLBXY"
    },
    {
        name: "Operating Systems and You: Becoming a Power User",
        issuer: "Google",
        issueDate: "02/2025",
        expirationDate: null,
        credentialUrl: "https://www.coursera.org/account/accomplishments/records/HT5K9NGRAJVW",
        licenseNumber: "HT5K9NGRAJVW"
    },
    {
        name: "macOS for IT Administrators",
        issuer: "LinkedIn",
        issueDate: "10/2023",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/103abbe52a84aadf812d827bb3574652879486b17517a99c5b7adf3f6f65183c",
        licenseNumber: null
    },
    {
        name: "Windows 10 for IT Pros Essential Training",
        issuer: "LinkedIn",
        issueDate: "09/2023",
        expirationDate: null,
        credentialUrl: "https://www.linkedin.com/learning/certificates/8c8e722df7a87dec2a515f5b5a6f943983b64c42099be0bd01a9f5610fe963d7",
        licenseNumber: null
    }
];

if (typeof module !== 'undefined') {
    module.exports = { CERTIFICATIONS: CERTIFICATIONS };
}

if (typeof window !== 'undefined') {
    window.CERTIFICATIONS = CERTIFICATIONS;
}
