// Generated by scripts/import-linkedin-export.js from your LinkedIn data export.
// Safe to hand-edit afterward — re-running the importer will overwrite this file,
// so commit hand-edits and review the diff on your next import.

var EDUCATION = [
    {
        school: "Texas State University",
        degree: "Bachelor of Science - BS",
        startDate: "08/2020",
        endDate: "12/2023",
        bullets: [

        ]
    },
    {
        school: "Austin Community College",
        degree: "Associate of Science - AS",
        startDate: "2015",
        endDate: "2019",
        bullets: [

        ]
    },
    {
        school: "Jack C Hays High School",
        degree: "High School Diploma",
        startDate: "2011",
        endDate: "2015",
        bullets: [

        ]
    }
];

if (typeof module !== 'undefined') {
    module.exports = { EDUCATION: EDUCATION };
}

if (typeof window !== 'undefined') {
    window.EDUCATION = EDUCATION;
}
