// Generated by scripts/import-linkedin-export.js from your LinkedIn data export.
// Safe to hand-edit afterward — re-running the importer will overwrite this file,
// so commit hand-edits and review the diff on your next import.
//
// Hand-trimmed to tech/IT-relevant roles after import — the full work history
// (general labor, retail, apprenticeships, etc. back to 2011) remains on the
// real LinkedIn profile, just not duplicated here.

var EXPERIENCE = [
    {
        title: "Software Engineer",
        company: "Q2",
        startDate: "08/2025",
        endDate: "Present",
        bullets: [

        ]
    },
    {
        title: "Information Technology Assistant",
        company: "Texas State University",
        startDate: "02/2023",
        endDate: "Present",
        bullets: [

        ]
    },
    {
        title: "Computer Repair Technician",
        company: "iTurity",
        startDate: "06/2025",
        endDate: "08/2025",
        bullets: [

        ]
    },
    {
        title: "Autonomous Vehicle Operator",
        company: "Manpower",
        startDate: "04/2025",
        endDate: "06/2025",
        bullets: [

        ]
    },
    {
        title: "IT Technician",
        company: "QA Systems Incorporated",
        startDate: "03/2024",
        endDate: "01/2025",
        bullets: [
            "As an IT Technician, I provide Tier 1 hardware support with a primary focus on repairing Chromebooks.",
            "My role involves diagnosing and resolving hardware issues efficiently, performing quality control (QC) checks, sorting inventory, and managing various other projects as assigned.",
            "Additionally, I maintain accurate records using advanced inventory management software to ensure seamless operations."
        ]
    },
    {
        title: "Computer Technician",
        company: "GTS Technology Solutions",
        startDate: "06/2023",
        endDate: "09/2023",
        bullets: [

        ]
    },
    {
        title: "Data Entry Clerk",
        company: "Xator Corporation",
        startDate: "06/2022",
        endDate: "08/2022",
        bullets: [

        ]
    }
];

if (typeof module !== 'undefined') {
    module.exports = { EXPERIENCE: EXPERIENCE };
}

if (typeof window !== 'undefined') {
    window.EXPERIENCE = EXPERIENCE;
}
