// Generated by scripts/import-linkedin-export.js from your LinkedIn data export
// merged with the hand-curated scripts/skillsCategoryMap.js. Re-running the
// importer overwrites this file — categorize new skills in skillsCategoryMap.js,
// not here.

var SKILLS = [
    {
        category: "Languages",
        skills: [
            { name: "BASH", icon: "img/icons/bash.png" },
            { name: "C", icon: "img/icons/c.webp" },
            { name: "C#", icon: "img/icons/c-sharp.png" },
            { name: "C++", icon: "img/icons/cpp.webp" },
            { name: "CSS", icon: "img/icons/css.png" },
            { name: "HTML", icon: "img/icons/html.png" },
            { name: "Java", icon: "img/icons/java.png" },
            { name: "JavaScript", icon: "img/icons/javascript.png" },
            { name: "PHP", icon: "img/icons/php.png" },
            { name: "PowerShell", icon: "img/icons/powershell.png" },
            { name: "Python", icon: "img/icons/python.png" },
            { name: "SQL", icon: "img/icons/sql.jpg" },
            { name: "T-SQL", icon: "img/icons/t-sql.svg" }
        ]
    },
    {
        category: "Frameworks & Libraries",
        skills: [
            { name: "Flask", icon: "img/icons/flask.png" },
            { name: "Matplotlib", icon: "img/icons/matplotlib.png" },
            { name: "Numpy", icon: "img/icons/numpy.png" },
            { name: "Pandas", icon: "img/icons/pandas.png" }
        ]
    },
    {
        category: "Databases & Data Tools",
        skills: [
            { name: "Microsoft SQL Server", icon: "img/icons/sql-server.svg" },
            { name: "MySQL", icon: "img/icons/mysql.png" },
            { name: "MySQL Workbench", icon: "img/icons/mysql-workbench.png" },
            { name: "Oracle", icon: "img/icons/oracle.png" }
        ]
    },
    {
        category: "Systems & DevOps",
        skills: [
            { name: "Active Directory", icon: "img/icons/active directory.jpg" },
            { name: "API Integration", icon: "img/icons/rest-api.png" },
            { name: "BitBucket", icon: "img/icons/bitbucket.png" },
            { name: "Git/GitHub", icon: "img/icons/git.png" },
            { name: "Linux", icon: "img/icons/linux.png" },
            { name: "Unix", icon: "img/icons/unix.png" },
            { name: "VMWare", icon: "img/icons/vmware.png" },
            { name: "Windows", icon: "img/icons/windows.png" },
            { name: "Windows Server", icon: "img/icons/windows server.png" }
        ]
    },
    {
        category: "Dev & Project Tools",
        skills: [
            { name: "Geany", icon: "img/icons/geany.png" },
            { name: "Jira", icon: "img/icons/jira.png" },
            { name: "Visual Studio", icon: "img/icons/visual studio.png" }
        ]
    },
    {
        category: "Web Services & Integration",
        skills: [
            { name: "WSDL", icon: "img/icons/wsdl.svg" },
            { name: "XML", icon: "img/icons/xml.svg" },
            { name: "SOAP", icon: "img/icons/soap.svg" }
        ]
    },
    {
        category: "Methodologies & Concepts",
        skills: [
            { name: "SDLC", icon: "img/icons/sdlc.svg" }
        ]
    }
];

if (typeof module !== 'undefined') {
    module.exports = { SKILLS: SKILLS };
}

if (typeof window !== 'undefined') {
    window.SKILLS = SKILLS;
}
