// Pure logic for turning LinkedIn's official "Get a copy of your data" CSV
// export into js/experienceData.js and js/skillsData.js. Node-only, never
// shipped to the browser. See scripts/import-linkedin-export.js for the CLI
// wrapper and README.md for the full manual workflow.

var MONTH_NAMES = {
    jan: '01', feb: '02', mar: '03', apr: '04', may: '05', jun: '06',
    jul: '07', aug: '08', sep: '09', oct: '10', nov: '11', dec: '12'
};

function normalizeHeader(header) {
    return String(header).trim().toLowerCase();
}

// headerRow: array of raw CSV header strings.
// aliasList: array of normalized (lowercase) header names accepted for this column.
// Returns the original header string as it appears in headerRow, or null.
function resolveColumn(headerRow, aliasList) {
    var normalizedAliases = aliasList.map(normalizeHeader);
    for (var i = 0; i < headerRow.length; i++) {
        if (normalizedAliases.indexOf(normalizeHeader(headerRow[i])) !== -1) {
            return headerRow[i];
        }
    }
    return null;
}

// Tolerant parser for LinkedIn's export date formats ("Feb 2023", "2023-02",
// "02/2023"). Blank input means "currently in this role" -> 'Present'.
// Never throws — unparseable input is returned as-is, with a warning.
function normalizeLinkedInDate(raw) {
    var trimmed = String(raw || '').trim();
    if (!trimmed) {
        return { value: 'Present', warning: null };
    }

    var monthYearMatch = trimmed.match(/^([A-Za-z]{3,})\s+(\d{4})$/);
    if (monthYearMatch) {
        var monthKey = monthYearMatch[1].slice(0, 3).toLowerCase();
        var monthNum = MONTH_NAMES[monthKey];
        if (monthNum) {
            return { value: monthNum + '/' + monthYearMatch[2], warning: null };
        }
    }

    var isoMatch = trimmed.match(/^(\d{4})-(\d{2})$/);
    if (isoMatch) {
        return { value: isoMatch[2] + '/' + isoMatch[1], warning: null };
    }

    if (/^\d{2}\/\d{4}$/.test(trimmed)) {
        return { value: trimmed, warning: null };
    }

    return { value: trimmed, warning: 'Could not confidently parse date "' + trimmed + '" — used as-is, please review.' };
}

// Splits a LinkedIn position "Description" field into bullet strings.
// Newline-delimited content is preferred; single-blob text falls back to a
// sentence-boundary heuristic. Imperfect by design — always review the diff.
function splitDescriptionIntoBullets(description) {
    var text = String(description || '').trim();
    if (!text) return [];

    var lines = text.split(/\r?\n/).map(function (line) { return line.trim(); }).filter(Boolean);

    var rawFragments = lines.length > 1
        ? lines
        : text.split(/(?<=[.!?])\s+(?=[A-Z•\-•])/);

    return rawFragments
        .map(function (fragment) {
            return fragment.replace(/^[•\-\*]\s*/, '').trim();
        })
        .filter(function (fragment) {
            return fragment.length > 2;
        });
}

function normalizeSkillName(name) {
    return String(name || '').trim().toLowerCase();
}

// Emits js/experienceData.js source text in the same hand-authored style used
// throughout the rest of the site (not raw JSON.stringify), so generated
// diffs read naturally against hand-edited history.
function buildExperienceDataFileSource(experienceArray) {
    var entries = experienceArray.map(function (entry) {
        var bulletsSource = entry.bullets
            .map(function (bullet) { return '            ' + JSON.stringify(bullet); })
            .join(',\n');
        return (
            '    {\n' +
            '        title: ' + JSON.stringify(entry.title) + ',\n' +
            '        company: ' + JSON.stringify(entry.company) + ',\n' +
            '        startDate: ' + JSON.stringify(entry.startDate) + ',\n' +
            '        endDate: ' + JSON.stringify(entry.endDate) + ',\n' +
            '        bullets: [\n' + bulletsSource + '\n        ]\n' +
            '    }'
        );
    }).join(',\n');

    return (
        '// Generated by scripts/import-linkedin-export.js from your LinkedIn data export.\n' +
        '// Safe to hand-edit afterward — re-running the importer will overwrite this file,\n' +
        '// so commit hand-edits and review the diff on your next import.\n\n' +
        'var EXPERIENCE = [\n' + entries + '\n];\n\n' +
        "if (typeof module !== 'undefined') {\n" +
        '    module.exports = { EXPERIENCE: EXPERIENCE };\n' +
        '}\n\n' +
        "if (typeof window !== 'undefined') {\n" +
        '    window.EXPERIENCE = EXPERIENCE;\n' +
        '}\n'
    );
}

// Merges a flat list of LinkedIn skill names with the hand-curated
// scripts/skillsCategoryMap.js. Unions rather than replaces: curated skills
// absent from a given export are never dropped. Unknown skills bucket into
// "Other" with no icon and a warning — never auto-guessed.
function mergeSkills(linkedinSkillNames, categoryMapModule) {
    var SKILL_CATEGORIES = categoryMapModule.SKILL_CATEGORIES;
    var SKILL_ALIASES = categoryMapModule.SKILL_ALIASES;
    var CATEGORY_ORDER = categoryMapModule.CATEGORY_ORDER;

    var warnings = [];
    var resolvedKeys = {};

    // Every curated skill is always included, regardless of what this
    // particular export contains.
    Object.keys(SKILL_CATEGORIES).forEach(function (key) {
        resolvedKeys[key] = true;
    });

    (linkedinSkillNames || []).forEach(function (rawName) {
        var normalized = normalizeSkillName(rawName);
        if (!normalized) return;
        var canonicalKey = SKILL_ALIASES[normalized] || normalized;

        if (SKILL_CATEGORIES[canonicalKey]) {
            resolvedKeys[canonicalKey] = true;
        } else {
            resolvedKeys['other:' + normalized] = { name: rawName.trim(), category: 'Other', icon: null };
            warnings.push('Unrecognized skill "' + rawName.trim() + '" — added under "Other" with no icon. Add it to scripts/skillsCategoryMap.js to categorize it.');
        }
    });

    var byCategory = {};
    Object.keys(resolvedKeys).forEach(function (key) {
        var entry = resolvedKeys[key] === true ? SKILL_CATEGORIES[key] : resolvedKeys[key];
        if (!byCategory[entry.category]) byCategory[entry.category] = [];
        byCategory[entry.category].push({ name: entry.name, icon: entry.icon });
    });

    var orderedCategories = CATEGORY_ORDER.concat(
        Object.keys(byCategory).filter(function (cat) { return CATEGORY_ORDER.indexOf(cat) === -1; })
    );

    var categories = orderedCategories
        .filter(function (cat) { return byCategory[cat] && byCategory[cat].length; })
        .map(function (cat) {
            return {
                category: cat,
                skills: byCategory[cat].sort(function (a, b) { return a.name.localeCompare(b.name); })
            };
        });

    return { categories: categories, warnings: warnings };
}

function buildSkillsDataFileSource(categories) {
    var categoriesSource = categories.map(function (categoryEntry) {
        var skillsSource = categoryEntry.skills.map(function (skill) {
            return (
                '            { name: ' + JSON.stringify(skill.name) +
                ', icon: ' + JSON.stringify(skill.icon) + ' }'
            );
        }).join(',\n');
        return (
            '    {\n' +
            '        category: ' + JSON.stringify(categoryEntry.category) + ',\n' +
            '        skills: [\n' + skillsSource + '\n        ]\n' +
            '    }'
        );
    }).join(',\n');

    return (
        '// Generated by scripts/import-linkedin-export.js from your LinkedIn data export\n' +
        '// merged with the hand-curated scripts/skillsCategoryMap.js. Re-running the\n' +
        '// importer overwrites this file — categorize new skills in skillsCategoryMap.js,\n' +
        '// not here.\n\n' +
        'var SKILLS = [\n' + categoriesSource + '\n];\n\n' +
        "if (typeof module !== 'undefined') {\n" +
        '    module.exports = { SKILLS: SKILLS };\n' +
        '}\n\n' +
        "if (typeof window !== 'undefined') {\n" +
        '    window.SKILLS = SKILLS;\n' +
        '}\n'
    );
}

if (typeof module !== 'undefined') {
    module.exports = {
        resolveColumn: resolveColumn,
        normalizeLinkedInDate: normalizeLinkedInDate,
        splitDescriptionIntoBullets: splitDescriptionIntoBullets,
        normalizeSkillName: normalizeSkillName,
        buildExperienceDataFileSource: buildExperienceDataFileSource,
        mergeSkills: mergeSkills,
        buildSkillsDataFileSource: buildSkillsDataFileSource
    };
}
